### PR TITLE
upgrade gui to pyqt5 and python3

### PR DESCRIPTION
**Pull request by flobbe**
The general components GUI now supports python3 and PyQt5

### CODE REVIEW

**Comment by exterm** [comment]
A PULL REQUEST! On disco-framework! In 2021!

**Comment by exterm** [comment]
Looks good to me; I will find some time to test the changes and then approve

**Comment by exterm** [comment]
```
$ make -sC priv/general/components/gui test
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/home/philip/projects/disco/priv/general/components/gui/./gui.py", line 454, in <module>
    win = MainWindow()
  File "/home/philip/projects/disco/priv/general/components/gui/./gui.py", line 20, in __init__
    self.ui.setupUi(self)
  File "/home/philip/projects/disco/priv/general/components/gui/ui_mainview.py", line 29, in setupUi
    self.centralwidget = QtGui.QWidget(MainWindow)
TypeError: QWidget(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = 0): argument 1 has unexpected type 'MainWindow'

make: *** [Makefile:22: test] Error 1
```

**Comment by flobbe** [comment]
Please try if it works for you now, I can't reproduce the problem here. It worked and works fine for me with the following versions:

- python2.7.12 + pyqt5.5.1 + qt5.5.1
- python3.5.2 + pyqt5.15.0 + qt5.15.0
- python3.8.1 + pyqt5.14.1 + qt5.12.8

Also I don't get the message "QSocketNotifier: Can only be used with threads started with QThread", but it should be solvable with the environment variable "QT_QPA_PLATFORM=xcb".
see https://stackoverflow.com/questions/60761280/qsocketnotifier-can-only-be-used-with-threads-started-with-qthread

**Comment by exterm** [comment]
Ah. I didn't `make clean` in the ui folder. I expected a `make clean` in the root folder to somehow clean everything.

**Comment by exterm** [comment]
What's up with the CI, doesn't seem to have run at all?

**Comment by exterm** [comment]
I think our CI broke when Travis decommissioned travis-ci.org. We could migrate to `.com` but I think at this poin tit makes more sense to migrate to github actions. Giving it a try in https://github.com/disco-framework/disco/pull/29

**Comment by exterm** [comment]
Github actions CI is working, I rebased this PR

**Pull request merged**
